name: drecipe
description: drecipe Mobile App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_route: ^4.2.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4

dev_dependencies:
  auto_route_generator: ^4.2.1
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # flutter_flavorizr: ^2.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios: null
  flavors:
    dev:
      app:
        name: "drecipe Development"
      android:
        applicationId: "com.drecipe.drecipe.dev"
      ios:
        bundleId: "com.drecipe.drecipe.dev"
    staging:
      app:
        name: "drecipe Staging"
      android:
        applicationId: "com.drecipe.drecipe.staging"
      ios:
        bundleId: "com.drecipe.drecipe.staging"
    prod:
      app:
        name: "drecipe"
      android:
        applicationId: "com.drecipe.drecipe"
      ios:
        bundleId: "com.drecipe.drecipe"
