abstract class FilterConstants {
  static const String cuisine = 'Cuisine';
  static const String mealType = 'Meal type';
  static const String diet = 'Diet';
  static const String intolerance = 'Intolerances';

  static const String sortAsc = 'ascending';
  static const String sortDesc = 'descending';

  static const List<String> cuisines = [
    'African',
    'American',
    'British',
    'Cajun',
    'Caribbean',
    'Chinese',
    'Eastern European',
    'European',
    'French',
    'German',
    'Greek',
    'Indian',
    'Irish',
    'Italian',
    'Japanese',
    'Jewish',
    'Korean',
    'Latin American',
    'Mediterranean',
    'Mexican',
    'Middle Eastern',
    'Nordic',
    'Southern',
    'Spanish',
    'Thai',
    'Vietnamese',
  ];

  static const List<String> diets = [
    'Gluten Free',
    'Ketogenic',
    'Vegetarian',
    'Lacto-Vegetarian',
    'Ovo-Vegetarian',
    'Vegan',
    'Pescetarian',
    'Paleo',
    'Primal',
    'Low FODMAP',
    'Whole30',
  ];

  static const List<String> filterTypes = [
    'cuisine',
    'diet',
    'intolerances',
    'type',
  ];

  static const List<String> intolerances = [
    'airy',
    'Egg',
    'Gluten',
    'Grain',
    'Peanut',
    'Seafood',
    'Sesame',
    'Shellfish',
    'Soy',
    'Sulfite',
    'Tree Nut',
    'Wheat',
  ];

  static const List<String> mealTypes = [
    'main course',
    'side dish',
    'dessert',
    'appetizer',
    'salad',
    'bread',
    'breakfast',
    'soup',
    'beverage',
    'sauce',
    'marinade',
    'fingerfood',
    'snack',
    'drink',
  ];

  static const List<String> sortingOptions = [
    'random',
    'meta-score',
    'popularity',
    'healthiness',
    'price',
    'time',
    'random',
    'max-used-ingredients',
    'min-missing-ingredients',
    'alcohol',
    'caffeine',
    'copper',
    'energy',
    'calories',
    'calcium',
    'carbohydrates',
    'carbs',
    'choline',
    'cholesterol',
    'total-fat',
    'fluoride',
    'trans-fat',
    'saturated-fat',
    'mono-unsaturated-fat',
    'poly-unsaturated-fat',
    'fiber',
    'folate',
    'folic-acid',
    'iodine',
    'iron',
    'magnesium',
    'manganese',
    'vitamin-b3',
    'niacin',
    'vitamin-b5',
    'pantothenic-acid',
    'phosphorus',
    'potassium',
    'protein',
    'vitamin-b2',
    'riboflavin',
    'selenium',
    'sodium',
    'vitamin-b1',
    'thiamin',
    'vitamin-a',
    'vitamin-b6',
    'vitamin-b12',
    'vitamin-c',
    'vitamin-d',
    'vitamin-e',
    'vitamin-k',
    'sugar',
    'zinc',
  ];
}
